In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [2]:
query1 = "Can I still join the course after the start date?"

vec1 = model.encode(query1)

vec1

array([ 2.13903859e-02, -7.39799738e-02,  1.42069475e-03,  2.13816315e-02,
        2.45113391e-02,  3.15582603e-02, -1.10839710e-01, -1.05017453e-01,
       -6.18258938e-02, -6.42312970e-03,  3.72394198e-03,  9.06393528e-02,
       -9.49937198e-03,  6.53976947e-02,  1.10946735e-02, -2.10097395e-02,
       -3.35125700e-02, -4.31677736e-02,  9.96346213e-03,  1.41969677e-02,
       -6.40415177e-02, -7.04179332e-03, -7.91188180e-02,  5.80030978e-02,
        1.30213588e-03,  4.19733720e-03,  5.70979156e-02,  6.39447868e-02,
        2.49903090e-02, -3.95876467e-02, -3.79506387e-02,  2.70394497e-02,
        1.79423485e-02,  1.72272474e-02,  3.43311429e-02,  9.29058157e-03,
        5.86054958e-02, -4.97789867e-02, -5.05369157e-03,  4.34328243e-02,
       -1.56622920e-02, -2.97534615e-02, -5.13324142e-03,  5.13414778e-02,
        6.16064621e-03,  6.86980411e-02, -1.29505135e-02, -5.61938696e-02,
       -1.08265216e-02,  5.96683659e-02,  5.29939905e-02, -3.42754982e-02,
       -4.15274203e-02, -

In [3]:
vec1.shape

(384,)

In [4]:
doc = "You don't need to register. You're accepted. You can also just start learning and submitting homework without registering."

doc_vec = model.encode(doc)

In [5]:
vec1.dot(doc_vec)

np.float32(0.32332397)

In [6]:
doc_vec.dot(vec1)

np.float32(0.32332397)

In [7]:
query2 = "How to install Docker on Windows?"

vec2 = model.encode(query2)

In [8]:
vec2.dot(doc_vec)

np.float32(0.019730574)

In [9]:
from ingest import load_faq_data

documents = load_faq_data()

In [10]:
documents[3]

{'id': '52217fc51b',
 'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: I have registered for the Data Engineering Bootcamp. When can I expect to receive the confirmation email?',
 'answer': "You don't need a confirmation email. You're accepted. You can start learning and submitting homework without registering. Registration was just to gauge interest before the start date."}

In [11]:
texts = []

for doc in documents:
    text = doc["question"] + " " + doc["answer"]
    texts.append(text)

In [12]:
len(texts)

1395

In [13]:
from tqdm.auto import tqdm

In [14]:
batch_size = 50
vectors = []

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i + batch_size]
    batch_vector = model.encode(batch)
    vectors.extend(batch_vector)

len(vectors)

  0%|          | 0/28 [00:00<?, ?it/s]

1395

In [15]:
vectors[10].shape

(384,)

In [16]:
import numpy as np

X = np.array(vectors)

In [17]:
X.shape

(1395, 384)

In [18]:
# vector * vector multiplication

scores = []

for i in range(0, len(vectors)):
    score = vec1.dot(vectors[i])
    scores.append(score)

scores

[np.float32(0.48740587),
 np.float32(0.2099193),
 np.float32(0.76294106),
 np.float32(0.44378525),
 np.float32(0.26083997),
 np.float32(0.4866516),
 np.float32(0.30061552),
 np.float32(0.56009984),
 np.float32(0.45960498),
 np.float32(0.25628167),
 np.float32(0.33153272),
 np.float32(0.27318522),
 np.float32(0.27691635),
 np.float32(0.34122986),
 np.float32(0.46007156),
 np.float32(0.26240277),
 np.float32(0.39200056),
 np.float32(0.10854157),
 np.float32(0.27567303),
 np.float32(0.16646828),
 np.float32(0.31437922),
 np.float32(0.0066854246),
 np.float32(0.11205028),
 np.float32(0.21905681),
 np.float32(0.3400085),
 np.float32(0.23571287),
 np.float32(0.32714826),
 np.float32(0.15088344),
 np.float32(0.16563272),
 np.float32(0.05545033),
 np.float32(0.23541182),
 np.float32(0.08533001),
 np.float32(-0.0030899644),
 np.float32(-0.042598374),
 np.float32(-0.060277097),
 np.float32(0.006491136),
 np.float32(0.034277484),
 np.float32(-0.049589746),
 np.float32(-0.0006707795),
 np.float32(

In [19]:
# another way

scores = [vec1.dot(X[i]) for i in range(len(vectors))]

scores

[np.float32(0.48740587),
 np.float32(0.2099193),
 np.float32(0.76294106),
 np.float32(0.44378525),
 np.float32(0.26083997),
 np.float32(0.4866516),
 np.float32(0.30061552),
 np.float32(0.56009984),
 np.float32(0.45960498),
 np.float32(0.25628167),
 np.float32(0.33153272),
 np.float32(0.27318522),
 np.float32(0.27691635),
 np.float32(0.34122986),
 np.float32(0.46007156),
 np.float32(0.26240277),
 np.float32(0.39200056),
 np.float32(0.10854157),
 np.float32(0.27567303),
 np.float32(0.16646828),
 np.float32(0.31437922),
 np.float32(0.0066854246),
 np.float32(0.11205028),
 np.float32(0.21905681),
 np.float32(0.3400085),
 np.float32(0.23571287),
 np.float32(0.32714826),
 np.float32(0.15088344),
 np.float32(0.16563272),
 np.float32(0.05545033),
 np.float32(0.23541182),
 np.float32(0.08533001),
 np.float32(-0.0030899644),
 np.float32(-0.042598374),
 np.float32(-0.060277097),
 np.float32(0.006491136),
 np.float32(0.034277484),
 np.float32(-0.049589746),
 np.float32(-0.0006707795),
 np.float32(

In [20]:
# or use maxtrix * vector multiplication

scores = X.dot(vec1)

In [21]:
scores

array([0.48740587, 0.2099193 , 0.762941  , ..., 0.20289944, 0.13746645,
       0.09721452], shape=(1395,), dtype=float32)

In [22]:
index = np.argmax(scores)


In [23]:
print("Index of highest cosine similarity: " + str(index))
print("Value of cosine similarity: " + str(scores[index]))

Index of highest cosine similarity: 2
Value of cosine similarity: 0.762941


In [24]:
documents[2]

{'id': '3f1424af17',
 'course': 'data-engineering-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'Course: Can I still join the course after the start date?',
 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute."}

In [25]:
# to get top 5 not just first highest

top5 = np.argsort(scores)[-5:]
top5

array([   7, 1009,  567, 1144,    2])

In [26]:
scores[top5]
    

array([0.56009984, 0.6536311 , 0.7192131 , 0.7579372 , 0.762941  ],
      dtype=float32)

In [27]:
# reverse
top5 = top5[::-1]
top5

array([   2, 1144,  567, 1009,    7])

In [28]:
for i in top5:
    print(scores[i])
    print(documents[i])
    print()

0.762941
{'id': '3f1424af17', 'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute."}

0.7579372
{'id': '2d8b16c2a0', 'course': 'mlops-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course - Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homeworks as long as the form is still open and accepting submissions.\n\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything to the last minute."}

0.7192131
{'id': '41aabbd7c5', 'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related 

In [29]:
top5 = np.argsort(-scores)[:5]

In [30]:
for i in top5:
    print(scores[i])
    print(documents[i])
    print()

0.762941
{'id': '3f1424af17', 'course': 'data-engineering-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course: Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homework.\n\nBe aware, however, that there will be deadlines for turning in homeworks and the final projects. So don't leave everything for the last minute."}

0.7579372
{'id': '2d8b16c2a0', 'course': 'mlops-zoomcamp', 'section': 'General Course-Related Questions', 'question': 'Course - Can I still join the course after the start date?', 'answer': "Yes, even if you don't register, you're still eligible to submit the homeworks as long as the form is still open and accepting submissions.\n\nBe aware, however, that there will be deadlines for turning in the final projects. So don't leave everything to the last minute."}

0.7192131
{'id': '41aabbd7c5', 'course': 'machine-learning-zoomcamp', 'section': 'General Course-Related 

## Lesson 5

In [31]:
from minsearch import VectorSearch

In [32]:
vindex = VectorSearch(keyword_fields=["course"])
vindex.fit(X, documents)

In [33]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

In [34]:
vindex.search(query_vector, num_results=5)

[{'id': '74eb249bbf',
  'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'I just discovered the course. Can I still join?',
  'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'},
 {'id': '41aabbd7c5',
  'course': 'machine-learning-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'The course has already started. Can I still join it?',
  'answer': 'Yes, you can. Even though you missed the start date, you can register for the course. You won’t be able to submit some of the homeworks, but you can still take part in the course.\n\nIn order to get a certificate, you need to submit 2 out of 3 course projects and review 3 peers by the deadline. It means that if you join the course at the end of November and manage to work on two projects, you will still be eligible for a certificate.'},
 {'id': '2d8b16c2a0',
  'course': 'mlops-zoomcamp',
  'section':

In [39]:
results = vindex.search(
    query_vector,
    filter_dict={"course" : "llm-zoomcamp"},
    num_results=5
)

results

[{'id': '74eb249bbf',
  'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'I just discovered the course. Can I still join?',
  'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'},
 {'id': '69d122f12e',
  'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  'question': 'Certificate: Can I follow the course in a self-paced mode and get a certificate?',
  'answer': 'No, you can only get a certificate if you finish the course with a "live" cohort.\n\nTo get the certificate, you need to finish a capstone project and complete the\nrequired peer reviews. Homework is not required. You can work through the\nmaterial and prepare your project in self-paced mode, but project submission and\npeer review must happen while a live cohort is accepting them.'},
 {'id': 'bd31146b0e',
  'course': 'llm-zoomcamp',
  'section': 'General Course-Related Questions',
  '

In [40]:
results[0]

{'id': '74eb249bbf',
 'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'}

## Lesson 6

In [41]:
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
openai_client = OpenAI()

In [42]:
from ingest import load_faq_data, build_index

documents = load_faq_data()
index = build_index(documents)

In [43]:
from rag_helper import RAGBase

assistant = RAGBase(
    index = index,
    llm_client = openai_client
)

In [45]:
query = "I just discovered the course. Can I still join it?"
assistant.rag(query)

'Yes, you can still join. If you want a certificate, make sure to submit your project while submissions are still being accepted.'

In [46]:
class RAGVector(RAGBase):

    def __init__(self, embedder, **kwargs):
        super().__init__(**kwargs)
        self.embedder = embedder

    def search(self, query, num_results=5):
        query_vector = self.embedder.encode(query)
        filder_dict = {"course" : "llm-zoomcamp"}

        return self.index.search(
            query_vector,
            filter_dict=filder_dict,
            num_results=num_results
        )


In [47]:
vector_assistant = RAGVector(
    embedder=model,
    index = vindex,
    llm_client = openai_client
)

In [48]:
vector_assistant.rag("the program has already begun, can I still sign up?")

'Yes, you can still join. If you want a certificate, make sure to submit your project while submissions are still being accepted.'

## Lesson 7

In [50]:
from sqlitesearch import VectorSearchIndex

vs_index = VectorSearchIndex(
    keyword_fields = ["course"],
    mode = "ivf",
    db_path = "faq_vectors.db"
)

In [51]:
vs_index.fit(X, documents)

In [52]:
query = "I just discovered the course. Can I still join it?"
query_vector = model.encode(query)

results = vs_index.search(query_vector, num_results=5)

In [53]:
reusults = vs_index.search(
    query_vector,
    filter_dict={"course" : "llm-zoomcamp"},
    num_results=5
)

results[0]

{'id': '74eb249bbf',
 'course': 'llm-zoomcamp',
 'section': 'General Course-Related Questions',
 'question': 'I just discovered the course. Can I still join?',
 'answer': 'Yes, but if you want to receive a certificate, you need to submit your project while we’re still accepting submissions.'}

In [54]:
vs_index.close()